### ISSUE TITLE
No audio sink available

### ISSUE THREAD

**Issue by zz85** [oampo/Audiolet#18]
Hi,

I'm running Chome 15.0.874.121 on a Mac OS 10.6.8 (snow leopard). Just wondering if anyone encounter this error "No audio sink available" when you try to make too many connections to audiolet in a short time? (Eg. in the user-guide examples, keep pressing "Run examples" and you would encounter this error in a few seconds)

Firefox 8 doesn't seem to have this problem, so I'm suspecting its my browser/plateform or perhaps I'm missing some code that doesn't release resources?

Thanks.

**Comment by oampo** [comment]
Ah yeah - this is probably an issue with how the examples are set up.  What should really happen is that we connect and disconnect nodes the Audiolet object rather than recreating it each time the run button is pressed.  I'll work on getting this fixed up, but for now just avoid creating more than one Audiolet object and you should be okay.

**Comment by zz85** [comment]
hmm.. what about multiple Synth objects, is there a limit? it seems that I encounter the same error with a single Audiolet object but using multiple Synth objects too...

**Comment by zz85** [comment]
ah, my bad. I realized I was creating `new Audiolet();` instances in my Synth objects. removed them to ensure only 1 instance of Audiolet is used and the issue is resolved. Thanks! =)
